### PR TITLE
Add branch alias to composer.json

### PR DESCRIPTION
**Pull request by joshdifabio**

### CODE REVIEW

**Comment by Flyingmana** [comment]
what is the benefit?

**Comment by joshdifabio** [comment]
It allows people to require `3.0` with minimum stability dev in order to pull in the development version of 3.0. Presently, the only way to pull in `master` is to require `dev-master` explicitly, but if people do this then they risk pulling in `4.0-dev`.

Presently I am using `"magento-hackathon/magento-composer-installer": "dev-master as 3.0@dev"`.

**Comment by joshdifabio** [comment]
Note that many of the major PHP projects use branch aliases for this reason (see [Composer](https://github.com/composer/composer/blob/master/composer.json#L47), [Symfony](https://github.com/symfony/symfony/blob/master/composer.json#L98), [ReactPHP](https://github.com/reactphp/react/blob/master/composer.json#L32))

**Comment by Flyingmana** [comment]
I dont see the reason here. if people are so "lightheaded" to require dev-master, they should be expecting things to break from time to time(even if I do my best to prevent this) 
And if they want to use something different they can do dev-3.0.

or they are ok with using ~3.0@dev which should for example pull also the latest dev release(which currently is 3.0.0-beta.1)


Or is there any reason why something like ~3.0@dev or dev-3.0 is problematic in a best practice environment?

**Comment by joshdifabio** [comment]
The latest release on this repo is `3.0.0-alpha.2`, and it seems to be broken (magento-force doesn't work).

The latest release on https://github.com/Cotya/magento-composer-installer (why are there two repo's being maintained..?) is 3.0.0-beta.1, but that doesn't work on PHP 5.3.

The only version which seems to work on PHP 5.3, and doesn't have any obvious bugs, is dev-master.

**Comment by Flyingmana** [comment]
the recommended source for packages is packages.firegento.com, so releases on there are the valid ones

**Pull request closed without merging**
